spring:
  jackson:
    time-zone: America/Bogota
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/db_pizza?createDatabaseIfNotExist=true
    password: duvan123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        SQL: debug
springdoc:
  api-docs:
    enabled: true
    path: /openapi/v3/api-docs
    packages: com.duvanlabrador.Pizzas.infrastructure.adapters.input.rest.controller
  swagger-ui:
    enabled: true
    path: /openapi/swagger-ui.html
  pathsToMatch: /**
